version: '3'
services:
  nginx:
    image: 216659404274.dkr.ecr.ap-southeast-2.amazonaws.com/dockerzon-nginx:1.1
    links:
      - express
    ports:
      - '80:80'
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-southeast-2
        awslogs-stream-prefix: dockerzon
        awslogs-multiline-pattern: '^DOCKERZON::'
        awslogs-group: /ecs/dockerzon/dev

  express:
    image: 216659404274.dkr.ecr.ap-southeast-2.amazonaws.com/dockerzon-express:1.1
    ports:
      - '8000:8000'
    environment:
      - NODE_ENV=production
      - NEXT_GOAL=SAPro
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-southeast-2
        awslogs-stream-prefix: dockerzon
        awslogs-multiline-pattern: '^DOCKERZON::'
        awslogs-group: /ecs/dockerzon/dev
