version: 1
task_definition:
  ecs_network_mode: bridge
  services:
    express:
      cpu_shares: 256
      mem_limit: 100m
    nginx:
      cpu_shares: 768
      mem_limit: 300m
  # placement_constraints:
  #     - type: memberOf
  #       # run services on instance with attribute equal to instanceTwo
  #       expression: "attribute:location == instanceTwo"
