# used for local dev
version: '3'

services:
  nginx:
    build: ./frontend
    container_name: nginx
    ports:
      - '4000:80'

  express:
    build: ./express
    container_name: express
    ports:
      - '8000:8000'
    volumes:
      - .:/express
    env_file:
      - ./express/.env
