version: 1
task_definition:
  services:
    express:
      cpu_shares: 256
      mem_limit: 100m
    nginx:
      cpu_shares: 768
      mem_limit: 300m
  placement_constraints:
      - type: memberOf
        expression: "attribute:location == instanceOne"
