# used for local dev
version: '3'

services:
  nginx:
    build: ./frontend
    container_name: nginx
    environment:
      - NODE_ENV=development
    ports:
      - '80:80'

  express:
    build: ./express
    container_name: express
    ports:
      - '8000:8000'
    volumes:
      - .:/express
    environment:
      - NODE_ENV=development
      - HOST=localhost
      - PORT=8000
