version: '3'
services:
  weatherApi:
    image: 216659404274.dkr.ecr.ap-southeast-2.amazonaws.com/dockerzon-weatherapi:latest
    ports:
      - '8000:8000'
    environment:
      - NODE_ENV=production
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-southeast-2
        awslogs-stream-prefix: weatherApi
        awslogs-multiline-pattern: '^weatherApi::'
        awslogs-group: /ecs/dockerzon/weatherApi
